site_name: Darik's School to Code Good
site_url: https://darikoneil.github.io/dariks_school_to_code_good
repo_name: dariks_school_to_code_good
repo_url: https://github.com/darikoneil/dariks_school_to_code_good
site_author: Darik A. O'Neil

nav:
    - Home: index.md
    - Chapters:
        - Preface:
            IDEs: lessons/preface/ides.md
            Virtual Environments: lessons/preface/venv.md
            Documentation: lessons/preface/docs.md
        - Introduction:
            - What is Programming?: lessons/introduction/what_is_programming.md
            - Programming Matters: lessons/introduction/programming_matters.md
            - Languages: lessons/introduction/languages_overview.md
        - Data Types:
            - Fundamentals: lessons/1_data_types/fundamentals.md
            - Numerics: lessons/1_data_types/numerics.md
            - Text: lessons/1_data_types/text.md
            - Booleans: lessons/1_data_types/booleans.md
        - Expressions:
            - Literals: lessons/2_expressions/literals.md
            - Variables: lessons/2_expressions/variables.md
            - Operators: lessons/2_expressions/operators.md
            - Comparisons: lessons/2_expressions/comparisons.md
        - Control Flow:
            - Conditionals: lessons/3_control_flow/conditionals.md
            - Iteration: lessons/3_control_flow/iteration.md
            - Matching: lessons/3_control_flow/matching.md
        - Functions & Scripts:
            - Defining Functions: lessons/4_functions/defining_functions.md
            - Parameters and Arguments: lessons/4_functions/parameters_and_arguments.md
            - Return Values: lessons/4_functions/return_values.md
            - Scripts vs. Functions: lessons/4_functions/scripts_vs_functions.md
            - Scope and Lifetime: lessons/4_functions/scope_and_lifetime.md
        - Data Structures:
            - Lists: lessons/5_data_structures/lists.md
            - Tuples: lessons/5_data_structures/tuples.md
            - Arrays: lessons/5_data_structures/arrays.md
            - Hash Map : lessons/5_data_structures/hash_map.md
            - Sets: lessons/5_data_structures/sets.md
        - Classes & Objects:
            - Defining Classes: lessons/6_classes/defining_classes.md
            - Attributes and Methods: lessons/6_classes/attributes_and_methods.md
            - Encapsulation: lessons/6_classes/encapsulation.md
            - Instantiation: lessons/6_classes/instantiation.md
        - Modules & Packages:
            - Libraries and Packages: lessons/7_modules/libraries_and_packages.md
            - Importing: lessons/7_modules/importing.md
        - Git:
            - Version Control Basics: lessons/11_git/version_control_basics.md
            - Branching and Merging: lessons/11_git/branching_and_merging.md
        - Debugging:
            - Error Types: lessons/8_debugging/error_types.md
            - Exception & Error Handling: lessons/8_debugging/exception_and_error_handling.md
            - Debugging Tools: lessons/8_debugging/debugging_tools.md
            - Linting and Static Analysis: lessons/8_debugging/linting_and_static_analysis.md
        - Testing:
            - Unit Testing: lessons/10_testing/unit_testing.md
            - Integration Testing: lessons/10_testing/integration_testing.md
            - Test-Driven Development: lessons/10_testing/test_driven_development.md
        - Advanced Topics:
            - Recursion: lessons/12_advanced_topics/recursion.md
            - Functional Programming: lessons/12_advanced_topics/functional_programming.md
            - Concurrency: lessons/12_advanced_topics/concurrency.md
            - Memory Management: lessons/12_advanced_topics/memory_management.md
    - About: about.md
    - Resources: resources.md
    - Contact: contact.md

theme:
  name: material
  custom_dir: overrides
  icon:
    admonition:
      abstract: material/lightbulb-on
  features:
    - header.autohide
#    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - toc.integrate
  font:
    text: Lexend
    code: Fira Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to auto mode
plugins:
  - search
  - tags

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - css/custom.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
